/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case
         * @description The case as a participant sees it: no points, no explanations.
         */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answers */
        post: operations["submit_answers_cases__case_id__submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard */
        get: operations["leaderboard_cases__case_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Structure a raw clinical text with an LLM. Returns a draft for the author to review
         *     and then POST to /cases; nothing is saved here.
         */
        post: operations["extract_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CaseIn
         * @description A clinical case with answer key, as written by a case author.
         */
        CaseIn: {
            /** Title */
            title: string;
            patient: components["schemas"]["Patient"];
            /** Presenting Complaint */
            presenting_complaint: string;
            /**
             * History
             * @description History of present illness, past history, medications.
             */
            history: string;
            vitals?: components["schemas"]["Vitals"];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Diagnosis Options */
            diagnosis_options: components["schemas"]["DiagnosisOption"][];
            /** Management Options */
            management_options: components["schemas"]["ManagementOption"][];
        };
        /** CasePublic */
        CasePublic: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Presenting Complaint */
            presenting_complaint: string;
            patient: components["schemas"]["Patient"];
            /** History */
            history: string;
            vitals: components["schemas"]["Vitals"];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Diagnosis Options */
            diagnosis_options: components["schemas"]["OptionPublic"][];
            /** Management Options */
            management_options: components["schemas"]["OptionPublic"][];
        };
        /** CaseSummary */
        CaseSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Presenting Complaint */
            presenting_complaint: string;
            patient: components["schemas"]["Patient"];
        };
        /** DiagnosisOption */
        DiagnosisOption: {
            /** Label */
            label: string;
            /**
             * Points
             * @description 10 = correct diagnosis, 1-5 = partially correct, 0 = wrong.
             */
            points: number;
            /**
             * Explanation
             * @description Why it is (in)correct. Shown after answering.
             */
            explanation?: string | null;
        };
        /** ExtractIn */
        ExtractIn: {
            /** Text */
            text: string;
        };
        /** Finding */
        Finding: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "exam" | "lab" | "imaging" | "ecg" | "other";
            /**
             * Name
             * @description What was examined or measured, e.g. 'Troponin I'.
             */
            name: string;
            /**
             * Value
             * @description Result with units, e.g. '2.1 ng/mL' or 'ST elevation II, III, aVF'.
             */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** Participant */
            participant: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** ManagementOption */
        ManagementOption: {
            /** Label */
            label: string;
            /**
             * Points
             * @description Positive = indicated (5 essential), 0 = neutral, negative = harmful (-5).
             */
            points: number;
            /** Explanation */
            explanation?: string | null;
        };
        /** OptionPublic */
        OptionPublic: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** Patient */
        Patient: {
            /**
             * Age
             * @description Age in full years.
             */
            age: number;
            /**
             * Sex
             * @enum {string}
             */
            sex: "female" | "male";
        };
        /** ScoredOption */
        ScoredOption: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "diagnosis" | "management";
            /** Label */
            label: string;
            /** Points */
            points: number;
            /** Explanation */
            explanation: string | null;
            /** Chosen */
            chosen: boolean;
        };
        /** SubmissionIn */
        SubmissionIn: {
            /** Participant */
            participant: string;
            /** Diagnosis Option Id */
            diagnosis_option_id: number;
            /** Management Option Ids */
            management_option_ids?: number[];
        };
        /** SubmissionResult */
        SubmissionResult: {
            /** Submission Id */
            submission_id: number;
            /** Case Id */
            case_id: number;
            /** Participant */
            participant: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Diagnosis Correct */
            diagnosis_correct: boolean;
            /**
             * Options
             * @description Full answer key with the participant's choices marked.
             */
            options: components["schemas"]["ScoredOption"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vitals
         * @description Vital signs at presentation. Null when not stated in the source.
         */
        Vitals: {
            /**
             * Heart Rate
             * @description Beats per minute.
             */
            heart_rate?: number | null;
            /**
             * Systolic Bp
             * @description mmHg.
             */
            systolic_bp?: number | null;
            /**
             * Diastolic Bp
             * @description mmHg.
             */
            diastolic_bp?: number | null;
            /**
             * Respiratory Rate
             * @description Breaths per minute.
             */
            respiratory_rate?: number | null;
            /**
             * Temperature C
             * @description Degrees Celsius.
             */
            temperature_c?: number | null;
            /**
             * Spo2
             * @description Oxygen saturation, %.
             */
            spo2?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
        };
    };
    create_case_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answers_cases__case_id__submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_cases__case_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseIn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
